# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user_id',
            new_name='user',
        ),
    ]
