# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_user_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='people',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='belt.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friends_with', through='belt.Friend', to='belt.User'),
        ),
    ]
