# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0005_auto_20180227_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='people',
        ),
        migrations.AddField(
            model_name='friend',
            name='from_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='belt.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='to_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='belt.User'),
            preserve_default=False,
        ),
    ]
